### ISSUE TITLE
记录第一次创业失败

### ISSUE THREAD

**Issue by icepy** [icepy/icepy.me#11]
回想今晚，坐在铁轨上喝着啤酒，脑袋里就想着我哥哥给我说的一句话：意料之中，创业你还太嫩了。呵呵，我以为会这样，我以为会怎样，谁又想到是这样呢？
- 一个人去实地考察，山里面，下暴雨
- 一个人去跑工商局，问情况
- 一个人跟乡政府的书记吃饭喝酒，掏了2000多
- 一个人写创业计划书给投资人
- 一个人写To List 一个月内的
- 一个人买了农业大学大一到大四的教科书
- 一个人在做市场调查
- 一个人在做预算报表
- 一个人在接待投资人，陪同去实地考察
- 一个人在写微信端和官网
- 一个人在做无土栽培和共生系统的实验

我都不知道，这是创业吗，还是我来给你们打工的。满腔热血，换来的是冷漠。

看看我跑来的成果，那又怎么样？农业怎么了？不体面吗？我们之间一点契约精神都没，说不搞就不搞撂挑子了。每个人都有自己的小盘算，是，我理解，那又怎么样？每次到了关键时刻，就开始退缩了。

各种理由，你爸妈不想你辞职，我今年还想拿年终奖，我还有点别的事情，那你来创个鬼的业，之前约定好的一起回来，说翻脸就翻脸，又只有我一个人回来。

我哥哥说的对，意料之中，创业你还太嫩了。

![](http://7qncz5.com1.z0.glb.clouddn.com/action/IMG_0575.png)

如果创业，年终奖这种风险，时间风险，你都承受不了，那你还来创个毛的业，都想赚钱又不想出力，天朝这种好事，怎么就轮不到我呢。

![](http://7qncz5.com1.z0.glb.clouddn.com/action/IMG_0573.png)

在离开携程之前，我们四个人在网络上就一起商量着能做些什么，于是我们想到了食品安全，我们想做生态农业，想做安全，放心的食材，我们觉得这非常有意义。

我们想到了在雪峰山这个大生态圈中去研究食材，我们想到了如何利用好H5技术去推广，营销，我们想到了如何利用好雪峰山这个生态圈去研究共生系统，我们想到了如何利用好移动互联网去跟需求安全，放心食材的客户对接。于是，我们下了决心，希望能朝着我们预期的目标前进。

在这里，我就犯了自己第一个错误，前期我很主动的去承担了评估的工作，在网上找数据，联系农业专家，给在林业局上班的表哥打电话要来雪峰山的土壤评估，能否去养殖和种植什么，看看市场的行情是怎样的。

我把这些东西整理成了一个小册子，用邮件写给了我的合伙人。

第一步总是美好和圆满的，对于前景我们也很有信心把它做好，而且如果我们做的好还能带动我们的族人一起，这个积极意义就更大了，不是么。

有了第一步的基础，很顺利的进入预估期，开始预估我们能承包多少地，我们的微信端和官方网站的开发周期，我们能种植养殖什么，确定了这一个目标，我们约定好了七月初六月底一起回到家乡，开创我们的事业。

2014年12月31日，我从携程辞职，回到了雪峰山，开始进行筹备工作，到这里为止，噩梦来了。

---

说好的一起回到家乡，却只有我一个人，那么就一个人吧，我又开始迁就我的团队成员，开始了漫长的一个人系列。

最后的结局是什么呢？一个合伙人的家里不允许他回来，因为农业，农民是不体面的工作，如果回来搞这个大学就白读了。一个合伙人希望能拿了年终奖再回来，不想前半年的时间都浪费了。说到这里，前面的好像都白说了，因为我回来了，损失的只是我一个人，前前后后花费的精力和金钱。

哥哥说的那句话，真的很讽刺我，我确实太嫩了。

我记得我们小时候都不是这样的，为什么人长大了，变成了这样。

很希望，我们还是这样的老房子，什么都未变，可是确实变了。

**Comment by icepy** [comment]
愿一切安好；

**Comment by sunyonggang** [comment]
good luck
:runner:

**Comment by yalishizhude** [comment]
创业还是需要积累经验，也需要运气~

**Comment by icepy** [comment]
@sunyonggang 3Q

**Comment by icepy** [comment]
@yalishizhude 是的，99%的汗水与经验，1%的运气。

**Comment by gongvirgil** [comment]
加油，创业还是要有一个好的团队的。

**Comment by cjpx00008** [comment]
有类似经历的飘过，支持下

**Comment by icepy** [comment]
@gongvirgil 是的，好的团队比任何事情都要重要，好的团队都能目标一致。

**Comment by icepy** [comment]
@cjpx00008  且行且珍惜……

**Comment by VectorHo** [comment]
多经历才能有更高层次

**Comment by sharkrice** [comment]
一个好团队的重要性

**Comment by sunliwen** [comment]
感觉这都不叫失败，只是经历。
