### ISSUE TITLE
学习React第一步

### ISSUE THREAD

**Issue by icepy** [icepy/icepy.me#13]
## 运行项目 Demo

关于如何配置启动React项目，可访问：[React&React Native初次体验](https://github.com/icepy/_posts/issues/7)

源代码Demo做了一些调整，可访问：[react-web](https://github.com/icepy/_posts/tree/master/demo/react-web)

Demo所使用的react，react-dom，react-router版本信息：
- react 版本信息 0.14.3
- react-dom 版本信息 0.14.3
- react-router 版本信息 1.0.0

下载Demo，然后：
- `npm install` 安装必要的node_modules模块
- `python -m SimpleHTTPServer 8900` 启动一个服务器
- 运行`gulp` 进行编译

最后访问：`http://127.0.0.1:8900/#/inbox` 来查看react编写的页面。
## 学习React第一步

**React设计思路**

在Web开发中，我们总是需要将数据的变化实时反映在UI上，这时就需要对DOM进行操作，大家都知道复杂和频繁的DOM操作是Web应用的性能瓶颈原因之一，如何高性能的操作DOM，这是一个考验前端开发者技能重要的指标。

React引入了虚拟DOM（Virtual DOM）来解决这个问题。用React开发的Web应用，看起来是整体都刷新了，其实在局部如何高性能的更新界面，React框架帮助我们做了很多事情。

阅读它，来了解React如何进行Diff比对，并更新界面。
- [虚拟DOM Diff算法解析](http://www.infoq.com/cn/articles/react-dom-diff)

**其实，待我看完React的文档之后，就让我联想到了很久很久之前的Web开发。服务端根据数据Render出一个完整的页面，然后响应给浏览器，如果用户在浏览器上进行了某些操作，改变了数据，服务器并不知道改变了哪些HTML，所以需要再根据变化的数据Render出一个完整的页面，再响应给浏览器。**

React在编程思路上，还引入了`一切皆组件`的原则，可能在一个页面中，会存在`header`，`footer`，`content`三个区域，React会认为，这个页面由三个组件来组成，也许`content`又分为`nav`，`list`，于是`content`组件又由`nav`，`list`来组成。由小组件装载到大组件，再由大组件装载成一个Web页面。

**看来组件是一个恒久的话题，经典的MVC结构可以让Web页面做到视图－数据－控制器的分离，开发者需要从技术的角度来将UI进行分离，比如将HTML碎片看做是视图，将请求看做是模型，将连接模型与视图的连接点看做是控制器，而组件化的方式可以让UI更加的抽象与模块化，React的设计思路就是需要开发者从功能的角度，将UI分成不同的组件，每一个组件都是独立封装，拥有自己的生命周期。**

**扯一个题外的话：MVVM的应用，个人比较喜欢vue.js，开发者对于Web页面进行了更颗粒度的分离，在模型与视图之间设置了一个viewmodel层来做桥接，而且是互通有无的。MVC看起来更关注的是C这一层，大量的业务逻辑在控制器中，也意味着有可能形成控制器臃肿的问题。**

**React编程**
- createElement （使用较少）
- createFactory（使用较少）

在还没有使用`JSX`语法之前，我想创建`React元素`（姑且这么说），我需要利用`createElement`来创建。

``` JavaScript
React.createElement('div', {}, 'Hello, world!')
```

而`createFactory`则是React提供的一个辅助我们快速创建Element对象的使用。

日常开发中最重要的两个类：
- createClass
- Component

大部分开发都有固定的模型，基本上都会基于这两个类来进行开发。`createClass`可以创建一个独立的React类，而`Component`从字面意思上来说，更清晰的表明它将创建一个组件，那么，问题来了，有何不同？

`FB原话是，希望在ES6中不要混淆了Class的创建，推荐在ES6中使用Component`

其实Componet是组件扩展，React自己就实现了大量的扩展

从编程的体验上来说，还是有些不同的

``` JavaScript
constructor(){
    super();
    this.state = {
        'indexDB':'v0.0.1'
    };
}

getInitialState(){
      return{
        router: window.location.hash.substr(1)
      };
}
```

state状态在ES6中需要写在`constructor`，而`createClass`则给予了我们`魔法方法：getInitialState`，也许现在你就明白了，没错`createClass`帮助我们自动绑定了`this`，`propTypes`和`getDefaultTypes`则要变成设置类属性。

**JSX**

虽然`JSX`语法看起来有些像XML，但是使用它比自己一层一层的去创建`createElement`好减少工作量，通过`gulp`或者`webpack`来进行语法转换，将极大的减少工作量。

``` JavaScript
render(){
    let value = '毫秒：'+this.props.date.getTime();
    let style = {
        paddingTop:'10px'
    };
    let buttonTop = {
        marginTop:'10px'
    };
    return(
        <div style={style}>
            <input type="text" placeholder="table view" defaultValue={value} onChange={this.handlerChange}/>
            <p>It is {this.props.date.toTimeString()}</p>
            <p>indexDB {this.state.indexDB}</p>
            <p ref="myIndexCoding">indexCoding {InputComponent.props.indexCoding}</p>
            <button style={buttonTop} type="button" className="am-btn am-btn-warning" onClick={this.fetchIndexCodingVersion.bind(this,event)}>获取 IndexCoding</button>
        </div>
    );
}   
```

没错，`JSX`就像平时我们写HTML页面一样，非常简单和非常方便的来构建Web应用。`{}`可以进行赋值或者来写表达式，`{/**/}`来书写注释，不过一般情况下，如果通过某个布尔值来显示UI，可以将判断写在`return`之前，也许这样结构会更清晰一些。

**state状态**

React的刷新机制是根据`state`来做的，每一次`state`的改变都会触发React框架来进行Diff比对，以及更新，我们可以设置一些默认state，然后使用`setState`方法来改变`state`，且让我们看一看`react-router`例子：

``` JavaScript
getInitialState(){
    return{
        router: window.location.hash.substr(1)
    };
}

window.addEventListener('hashchange',()=>{
    this.setState({
        router:window.location.hash.substr(1)
    });
});
```

**props数据**

React将props视作你的数据来源，而几个不同的组件，从上到下传递数据，都将在props中获取，其实我更认为将它看作组件之前`通信`数据的桥梁。一般情况下，可能会将从请求中获取的数据，装载在一个自定义的属性中，只在自己这个组件的周期内有效。

可能会存在下面一种情况，当我定义一个组件`A`和`B`时，`B`的数据（请求参数）来源于组件`A`的某些操作所获取的数据，于是我需要在组件`A`中将这个数据（请求参数）传递给`B`，于是`props`就排上用场了。

``` JavaScript
<InputComponent date={new Date()}/>

let value = '毫秒：'+this.props.date.getTime();
let style = {
    paddingTop:'10px'
};
let buttonTop = {
    marginTop:'10px'
};
return(
    <div style={style}>
        {/*输入框*/}
        <input type="text" placeholder="table view" defaultValue={value} onChange={this.handlerChange}/>
        <p>It is {this.props.date.toTimeString()}</p>
        <p>indexDB {this.state.indexDB}</p>
        <p ref="myIndexCoding">indexCoding {InputComponent.props.indexCoding}</p>
        <button style={buttonTop} type="button" className="am-btn am-btn-warning" onClick={this.fetchIndexCodingVersion.bind(this,event)}>获取 IndexCoding</button>
    </div>
);
```

组件`B`通过`this.props.date`来获取组件`A`传递的数据。

**生命周期**

每一个组件都有它自己的生命周期，这个其实没多少说的，每一个方法都是固定的，牢记吧。
- componentWillMount
- componentDidMount
- componentWillReceiveProps
- shouldComponentUpdate
- componentWillUpdate
- componentDidUpdate
- componentWillUnmount

详细可阅读：[Component Specs and Lifecycle](https://facebook.github.io/react/docs/component-specs.html)

**获取DOM元素**

某些时候可能会需要用到操作DOM元素，于是这里就排上用场了。

定义一个`ref="myIndexCoding"`，然后通过`this.refs`来获取，而且`ref`还能做一次表达式。

**受限的表单**

在React中对表单进行了限制，如果设置了`value`属性，这说明它是一个受限表单，所谓的受限表单指的是在输入时不会跟着改变表单的`value`。这一决定，是根据DOM的特性而来，在输入了某些值的时候`value`发生了改变，但是通过`getAttribute`来获取值时依然会返回初始值。

如果不设置value，那么它就将是一个不受限的表单，跟普通正常表单一样。如果想给组件设置一个非空值，可以使用`defaultValue`来设置。

``` JavaScript
render(){
    let value = '毫秒：'+this.props.date.getTime();
    let style = {
        paddingTop:'10px'
    };
    let buttonTop = {
        marginTop:'10px'
    };
    return(
        <div style={style}>
            {/*输入框*/}
            <input type="text" placeholder="table view" defaultValue={value} onChange={this.handlerChange}/>
            <p>It is {this.props.date.toTimeString()}</p>
            <p>indexDB {this.state.indexDB}</p>
            <p ref="myIndexCoding">indexCoding {InputComponent.props.indexCoding}</p>
            <button style={buttonTop} type="button" className="am-btn am-btn-warning" onClick={this.fetchIndexCodingVersion.bind(this,event)}>获取 IndexCoding</button>
        </div>
    );
}

handlerChange(event){
    this.setState({
        tableValue:event.target.value.substr(0,50),
        indexDB:'v0.0.'+this.inputIndex++
    });
}
```

React是根据`状态`来做处理的，所以我们可以使用`setState`来改变。

**Comment by icepy** [comment]
React会编写一个系列，有运用心得，理论理解，最重要的是，每一篇文章都将配有Demo，欢迎大家持续关注。

**Comment by luqin** [comment]
@icepy :+1:  分享下我写的react与echarts集成的例子，希望对你有帮助：https://github.com/luqin/echarts-webpack-starter-kit

**Comment by icepy** [comment]
@luain 我还在实现一个Flux架构，一步一步来，集成和如何组织一个大型Web应用最后完结篇写。

**Comment by luqin** [comment]
为啥不 redux 呢？

**Comment by luqin** [comment]
为啥不 webpack 呢？

**Comment by icepy** [comment]
redux不也是简化Flux，我觉得学习一个东西，拿来用可以也要对这样设计架构有所认知。Flux实现，可不止redux一家。webpack只是资源模块构建工具，如果只写JS，用browserify都可以，所以用什么不重要，重要的是要根据具体的场景来选择使用什么。
