### ISSUE TITLE
webpack在PC项目中的应用

### ISSUE THREAD

**Issue by icepy** [icepy/icepy.me#25]
好东西，总是要使用的。
## webpack是什么工具

_webpack is a module bundler_

正如官网对webpack的描述，它是一种模块化加载器，当然也不仅仅限于此。某种程度上来说，可以代替某些`gulp`的功能，至少有些还是无法替代的。在webpack中所有的资源都会被视作模块来处理，为了应对这样的情况，webpack有对应的`loader`机制来处理，另外shim，plugins，和其他构建工具，一样一样的，更多的细节，需要你在实际的应用中慢慢去体会了。
## webpack的使用方法

安装：npm install webpack --verbose --save-dev

webpack认为一个项目（或者一个页面），总有一个入口文件，就像C语言中总有一个main函数一样。假设，我们创建两个文件`./mian.js`和`./query.js`，并且将`main.js`做为我们项目的入口文件。

`query.js`

``` JavaScript
    module.exports = function(){
         var version = 1.0.0;
         console.log(version)
    }
```

`main.js`

``` JavaScript
    var query = require('./query');
    query();
```

创建一个webpack.config.js文件

``` JavaScript
    var config = {
        entry:'./main.js',
        ouptut:{
            path:'./js'
            filename:'main.js'
        }
    }
    module.exports = config;
```

在你的终端上运行`webpack`即可。
## webpack配置详解

`entry`：

entry属性做为可配置的入口，比如上面所写的`./main.js`。entry有三种写法，每一个入口可以称之为一个chunk。
- 如果为字符串，只会打包一个`顺序依赖`的模块，输出则根据output配置而定。
- 如果为数组，只会打包一个`顺序依赖`的模块，合并到最后一个模块时导出，输出则根据output配置而定。
- 如果为对象，则会根据入口打包多个`顺序依赖`的模块，key名会根据在output的配置输出。

`output`：

输出规则，在此对象中设置。
- path 设置输出的文件路径
- filename 设置输出文件名，filename可以有多种配置，比如`main.js`，`[id].js`，`[name].js`，`[hash].js`等
- publicPath 设置资源的访问路径
- library 设置模块导出的类名
- libraryTarget:'umd' 设置模块兼容模式
- umdNamedDefine:true  同上

`devtool`：

将devtool设置为`source-map`，在开发调试阶段非常有用，它的模式非常多，我有搞的比较晕。

`loader`：

loader机制应该是webpack中非常重要的部分了，它是一系列资源的最终执行者。一般情况下，你可以访问：[webpack loader](http://webpack.github.io/docs/list-of-loaders.html)来访问可用loader列表。

比如现在我想将.html类型的文件，当做一个模块来载入。

```
npm install raw-loader
```

``` JavaScript
    module:{
        loaders:[
            {
                test:/\.html$/,
                loader:'raw',
                exclude:/(node_modules)/
            }
        ]
    }
```

每一个loader都可以用一个对象来描述，test是你的匹配规则，loader是你要载入的loader，exclude是你在执行规则是想忽略的目录。

`plugins`：

webpack的插件机制也非常的重要，其内置了多种插件，比如混淆，压缩等等。插件列表可以访问：[list of plugins](http://webpack.github.io/docs/list-of-plugins.html)。

正常情况下可以使用官方自带的插件：

``` JavaScript
    new webpack.optimize.UglifyJsPlugin({
        compress: {
            warnings: false
        }
    })
```

当然，我们也可以引入第三方插件，使用你的npm install吧。

`resolve`：

此配置可以对一些常用模块设置别名，比如`a.js`放置在`./src/module/address/`中，每次载入模块需要var a = require('./src/module/address/a');名字非长，如果设置别名了，只需要var a = require('a')；

``` JavaScript
    resolve:{
        alias:{
            "RequestModel":path.resolve(__dirname,'src/lib/request.model')
        }
    },
```

还可以设置访问路径，以及模块载入后缀。

``` JavaScript
    resolve:{
        root:path.resolve(filePath,'/src'),
        extensions:['','.js']
    }
```

`externals`：

此项配置可以将某些库设置为外部引用，内部不会打包合并进去。

``` JavaScript
    externals:{
        jquery:'window.jQuery'
    }
```
## 在我们PC项目中的应用

我们公司内部的项目，也开始应用npm scripts来做执行钩子，webpack来做构建，首先设计三个命令：
- npm run start
- npm run dev
- npm run build

**配置npm run start**

本地服务器的启动，我们没有使用webpack官方提供的webpack-dev-server，而是采用了 browser-sync。

``` JavaScript
var browser = require('browser-sync');
var browserSync = browser.create();
var PORT = 4000
var loadMap = [
    'modules/*.*',
    'src/**/*.*',
    './*.html',
       './web/*.html'
];
gulp.task('server',[], function() {
    // content
        browserSync.init({
            server:'./',
            port:PORT
        });
        gulp.watch(loadMap, function(file){
            console.log(file.path)
            browserSync.reload()
        });
});
```

利用gulp写了一个脚本任务，在package.json文件中设置：

``` JavaScript
    scripts:{
        "start":"gulp server"
    }
```

**了解我们项目的实际需求**

我们的项目是一个多页面项目，并不像单页应用一样（业务编程可以打包成一个），首先我们需要设计一个良好的目录结构，如下：
- web 目录放置*.html页面
- style 目录放置*.css文件，另外在此目录中放置了less源文件
- src 目录放置了我们的所有*.js文件
- mock  内置的模拟数据，放置在此
- img 图片放置目录
- link npm下载不了的第三方库放置在此
- YYT_PC_Modules 内部编写的模块，放置在此
- YYT_PC_Component 内部编写的组件，放置在此

编写一个map.json文件，用来维护多入口的关系。当然我们的webpack.dev.config.js文件，放置在根目录。最后的build阶段应该输出一个新的目录`dist`这个目录中放置的应该是所有build完成的资源，包括*.html文件。

它应该才是我们最终的发布目录。

**配置npm run dev**

对于CSS我们的期望是一个新的link而不是style内嵌，所以还需要做一些额外的事情，先下载loader和插件。

列表：

```
"less-loader": "^2.2.2",
"raw-loader": "^0.5.1",
"style-loader": "^0.13.0",
"css-loader": "^0.23.1",
"eslint": "^2.2.0",
"eslint-loader": "^1.3.0",
"extract-text-webpack-plugin": "^1.0.1",
```

`raw-loader`主要用来解决模板载入的问题，模块当做一个变量直接载入到业务编程中。

配置我们的CSS：

``` JavaScript
   // webpack.dev.config.js
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var extractLESS = new ExtractTextPlugin('../style/[name].css');
    {
        test: /\.less$/i,
        loader: extractLESS.extract(['css','less'])
    }

    //入口js文件

    require('../style/less/index.less')
```

`ExtractTextPlugin`的作用就是将CSS单独输出一个文件，这个文件名依赖于entry写的入口文件名。

配置我们的多页面JS：

``` JavaScript
    //利用了entry的对象写法
    {
        "index.main":"./src/index.mian.js"
    }

    //然后在输出是用[name]代替之前的'index.main.js'
```

提取JS文件中的公共部分：

webpack自带的一个插件，可以提取合并打包时的公共部分，只要在页面载入时，放置在合并打包后文件的前面。

``` JavaScript
new optimize.CommonsChunkPlugin('common.js')
```

**完整的dev构建脚本**

``` JavaScript
var webpack = require('webpack');
var path = require('path');
var fs = require('fs');
var plugins = [];
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var optimize = webpack.optimize
var extractLESS = new ExtractTextPlugin('../style/css/[name].css');
plugins.push(extractLESS);
plugins.push(new optimize.CommonsChunkPlugin('common.js'));
var sourceMap = require('./map.json').source;
var YYT_PC_Modules = 'link/YYT_PC_Modules/';
var YYT_PC_Component = 'link/YYT_PC_Component/';
var config = {
    entry: sourceMap,
    output: {
        path: path.resolve(__dirname + '/js'),
        filename: '[name].js'
    },
    devtool: 'source-map',
    module: {
        loaders: [
            {
                test: /\.html$/,
                loader: 'raw',
                exclude: /(node_modules)/
            },
            {
                test: /\.js$/,
                loader: 'eslint-loader',
                exclude: /(node_modules)/
            },
            {
                test: /\.less$/i,
                loader: extractLESS.extract(['css', 'less'])
            },
            {
                test: /\.(png|jpg)$/,
                loader: 'url-loader?limit=8192'
            }
        ]
    },
    plugins: plugins,
    resolve: {
        alias: {
            "tplEng": path.resolve(__dirname, 'link/template'),  //模板引擎
            "BaseModel": path.resolve(__dirname, YYT_PC_Modules + 'baseModel'),
            "BaseView": path.resolve(__dirname, YYT_PC_Modules + 'baseView'),
            "store": path.resolve(__dirname, YYT_PC_Modules + 'store/locationStore'),
            "cookie": path.resolve(__dirname, YYT_PC_Modules + 'store/cookie'),
            "url": path.resolve(__dirname, YYT_PC_Modules + 'util/url'),
            "tools": path.resolve(__dirname, YYT_PC_Modules + 'util/tools'),
            "FlashAPI": path.resolve(__dirname,YYT_PC_Modules + 'util/FlashAPI'),
            "DateTime": path.resolve(__dirname, YYT_PC_Modules + 'util/DateTime'),
            "pwdencrypt": path.resolve(__dirname, YYT_PC_Modules + 'crypto/pwdencrypt'),
            "secret": path.resolve(__dirname, YYT_PC_Modules + 'crypto/secret'),
            "UploadFile": path.resolve(__dirname, YYT_PC_Component + 'feature/UploadFile'),
            "AjaxForm": path.resolve(__dirname, YYT_PC_Component + 'feature/AjaxForm'),
            "Scrollbar": path.resolve(__dirname, YYT_PC_Component + 'feature/Scrollbar'),
            "LoginBox": path.resolve(__dirname, YYT_PC_Component + 'business/LoginBox/'),
            "UserModel": path.resolve(__dirname, YYT_PC_Component + 'business/UserModel/'),
            "UploadFileDialog": path.resolve(__dirname, YYT_PC_Component + 'business/UploadFileDialog/'),
            "ui.Dialog": path.resolve(__dirname, YYT_PC_Component + 'ui/dialog/'),
            "ui.Confirm": path.resolve(__dirname, YYT_PC_Component + 'ui/confirm/'),
            "ui.MsgBox": path.resolve(__dirname, YYT_PC_Component + 'ui/msgBox/'),
            "config": path.resolve(__dirname, 'src/lib/config')
        }
    },
    externals: {
        jquery: 'window.jQuery',
        backbone: 'window.Backbone',
        underscore: 'window._'
    }
};
// console.log(path.resolve(__dirname,'node_modules/jquery/dist/jquery.js'))
module.exports = config;

```

**问题**

问题一：在windows机器上如果你要设置环境变量（也许是我没有找到问题的所在，但是提出来，主要是Mac用习惯了。）

``` JavaScript
    scripts:{
        "dev":"WEB_PACK=1 webpack --watch --config webpack.dev.config.js "
    }
```

在webpack.dev.config.js文件中不能正确的获取环境变量，所以重新写了一个build文件，webpack.build.config.js来做最后的构建。

问题二：构建之后的文件hash化后如何更新HTML中的路径

这个问题，最后没有采用webpack来做，而是使用gulp来解决的。（不知道大家有没有什么好的方式）

感谢@sharkrice告知  HtmlWebpackPlugin  插件

问题三：构建系统的shim

我们的PC项目（兼容IE8+），依然使用着以前的库，jQuery.js，underscore.js，backbone.js，以及其他第三方不支持commonjs语法的插件，有很多兼容不是很好，最后还是写了另外一个入口文件（包装），然后在webpack合并打包的文件之前引入这些插件，挂载在一个全局的命名空间下，利用新写的一个包装入口导出模块。

问题四：CSS依赖重复

感谢@sharkrice 告知 尝试webpack.optimize.DedupePlugin，问题解决。

**Comment by sharkrice** [comment]
问题二：对于html中的路径都是用require()去获取，而不是用‘./’这些的路径去获取
问题三：用webpack.ProvidePlugin来把这些暴露出全局变量也不能用吗？
```
new webpack.ProvidePlugin({
    $: "jquery",
    jQuery: "jquery",
    "window.jQuery": "jquery"
})
```
问题四：用webpack.optimize.DedupePlugin试试

**Comment by icepy** [comment]
@sharkrice

问题三：我是使用了webpack.ProvidePlugin，但是合并的时候依然打到新文件里了，这个问题跟机器有关么？我公司里是windows，在家里的（Mac系统）没有这个问题。

问题二：你的意思是在index.html文件里require？

目前，我面临的问题可能是这样的：

我有一个index.html页面

```HTML
<html>
   <head></head>
  <body>
      <script src="./js/index.main.js"></script>
  </body>
</html>
```

npm run build之后，在js目录中是一个dfsdfdg222334.js（只是描述一下，类似这样的文件），面临如何将index.html中的script标签src 的引用变成dfsdfdg222334.js。（我们这个是多页面，所以有多个入口文件）

问题四：好的，我先尝试一下这个，谢谢哈；

**Comment by sharkrice** [comment]
@icepy 
问题三我没看明白，打到新文件是什么意思呢？
如果你要把这样另外打包的话，就要用CommonsChunkPlugin额外配置，你是因为这些库全打到bundle里然后就不能用了么？
或者你是要用到变量的话那有一个下策是用expose-loader。
不过我的理解是，你们不要把这些库给打包，用cdn或当成public资源直接从页面里引用，然后用externals获取全局变量转成模块，然后你们入口文件中当成模块直接引用。

问题二我误解了，我以为你的是组件或模板页面，你是这种传统html多页面的话，就要用另外的插件，HtmlWebpackPlugin，可以将脚本注入到html里，当然，会在output里生产新的html页面，原来的页面要当成模板用。

**Comment by icepy** [comment]
@sharkrice  

问题二，这个插件[HtmlWebpackPlugin]() ，谢谢提供。

问题三，的情况可能是这样的。

比如a.js

```Javascript
// npm install backbone
var Backbone = require('backbone');
```

实际情况肯定不能让backbone也和业务编程（bundle.js）打包合并在一起，而是要引入文件。最终的结果，我自己的期望是能不能做到像requirejs，配置shim这样。

我现在的解决办法就是利用externals设置，然后在外部引用<script></script>标签的方式做的。然后a.js变成了：

```Javascript
var Backbone = window.Backbone;
```

多页面的公共部分，可以用CommonsChunkPlugin这个插件提取的。

**Comment by sharkrice** [comment]
@icepy 
其实你不要用requirejs的意思去搞
其实就两种方法
一是在页面中用script标签引入，再用externals拿全局变量，然后就在入口中引用了。
另一种是npm install 这些库，用CommonsChunkPlugin提取这些库和业务分开，然后直接在入口中引用。

**Comment by icepy** [comment]
@sharkrice 上午还是用了externals的方式做了处理，前面去纠结这个问题，完全是钻了牛角尖了。

**Comment by sharkrice** [comment]
@icepy webpack我可是用了一星期去看文档才理解了它的思想理念

**Comment by yuanxj1024** [comment]
如果是PC端不是SPA的话，还要考虑异步加载的问题，这样某些js，css可以按需加载进来，不需要都打包到一个css文件或者js文件，尤其是自定义的组件或者模块，怎么处理？

**Comment by icepy** [comment]
@yuanxj1024 可以利用entry的对象描述和CommonsChunkPlugin插件，解决按需加载的。前者，打包不同的入口文件，后者智能提取公共部分，然后在页面中分别引入这些文件<script></script>。

比如一个页面index.html，其中有两个功能，A,B。分别写两个入口文件a.js和b.js。

```html
<script src="a.js"></script>
<script src="b.js"></script>
```

如果是自定义组件，A和B两个入口文件中都有引入，那么可以使用CommonsChunkPlugin提取一个common.js，在页面中写入：

```html
<script src="common.js"></script>
<script src="a.js"></script>
<script src="b.js"></script>
```

**Comment by sharkrice** [comment]
额，又从开发者头条点进来了，问题一：
在windows下我是这样写的
```
set WEB_PACK=1&&webpack --watch --config webpack.dev.config.js
```
但是后来我就用和你一样的方法，分别写成两个配置，分为开发和生产
再后来我发现原来npmjs有个插件都cross-env，用来统一Linux,mac,windows的开发环境的命令，但我没用过。

**Comment by icepy** [comment]
@sharkrice  哈哈，看来头条君给我传递了好多流量啊，个人觉得还是分开比较好。

**Comment by riskers** [comment]
map.json 是怎么样的？

**Comment by icepy** [comment]
@riskers 我只是把entry抽离出来了，就是一个JSON对象

**Comment by riskers** [comment]
请问怎么发布到线上呢？线上CDN地址有多个，怎么处理呢？

**Comment by ufologist** [comment]
对于问题三可以试一试 [Shimming modules/import-loader](http://webpack.github.io/docs/shimming-modules.html)

```javascript
// lib-global.js
// 全局模块
(function(global) {
    global.libGlobal = {
        sayHello: function() {
            console.log('mod', 'local global module');
        }
    };
})(this);
```

```javascript
// index.js
// local global module
var libGlobal = require('lib-global.js');
libGlobal.sayHello();
```

```javascript
// webpack.config.js
    module: {
        loaders: [{
            test: /lib-global\.js/,
            // http://webpack.github.io/docs/shimming-modules.html
            // imports: 将 window 依赖导入为 this
            //          .call(window);
            // exports: 将 libGlobal 导出为模块
            //          module.exports = libGlobal;
            loader: 'imports?this=>window!exports?libGlobal'
        }]
    }
```

完整的代码可以参考 [webpack-driven-web](https://github.com/appbone/webpack-driven-web)

**Comment by riskers** [comment]
@icepy 
好的，谢谢。请问你们的发布到线上是怎样的过程，因为最近我们也在尝试自动化上线，遇到了一些问题。

**Comment by icepy** [comment]
@riskers 可以不用，只需要在入口文件里require一个CSS入口文件，其它的引入就都在一个CSS入口文件里完成。CDN地址替换，目前我们是利用设置外部模块的方式。

   externals: {
        // require("jquery") 是引用自外部模块的
        // 对应全局变量 jQuery
        "jquery": "jQuery"
   }

然后这个文件，需要在引入webpack打包文件之前。

**Comment by riskers** [comment]
@icepy 那是jquery，但是自己写的js应该怎么上传CDN呢

**Comment by icepy** [comment]
@riskers  那你需要用一个插件，具体怎么使用的，你得查一下了。[https://github.com/ampedandwired/html-webpack-plugin](https://github.com/ampedandwired/html-webpack-plugin)
