### ISSUE TITLE
 如何管理你的编程时间

### ISSUE THREAD

**Issue by icepy** [icepy/icepy.me#27]
很多人会不会有这样的感受？每天，不知道自己的时间在处理哪些事情上，在忙些什么。虽然Todo应用解决了我们Task的分解以及提醒，但是它并没有给予我们可以分析这一段时间点内处理事情的数据。如果你想成为一个高效的程序员，你应该了解的工作实况。

[WakaTime](https://wakatime.com/)更好的帮助你记录你的Code时间，完善的图表分析，以及高效的管理，而且它支持多种多样的编辑器，IDE，这货可谓说是不可多得的佳作。

**使用WakaTime的好处**
- 分析自己的编码时间，看看时间都去哪了，方便自己以后更加高效的分配时间
- 统计自己平时代码中不同的语言占比
- 分享给好友

这玩意使用非常的简单，首先在官网上注册一个帐号：[注册WakaTime](https://wakatime.com/signup)，个人推荐使用sign up with [Github]()。

免费版和付费版唯一的不同是导出数据的周期，免费版只可以导出7天的数据，如果大家觉得好用还是推荐付费专业版地址：[pricing](https://wakatime.com/pricing)

待你注册完成之后，点击[settings](https://wakatime.com/settings)来获取你的唯一key。
## Sublime Text 3 配置WakaTime

全部的配置可访问：[config download](https://wakatime.com/download)。

做为前端，这里主要讲讲配置Sublime Text 3，配置起来真的非常方便。
- shift+command+p 调出命令编辑器，输入`install package`
- 输入wakatime，安装
- 在安装快结束时，会要求你输入API Key

现在你可以使用Sublime Text 3来进行编程了，如果想查看数据，可以访问[https://wakatime.com/dashboard](https://wakatime.com/dashboard) 。

**Comment by yalishizhude** [comment]
二维码都挂了啊。。。
